Implementation/IepProjekat/WebRole1/Controllers/QuestionController.cs
using log4net;
using System;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using WebRole1.Models;

namespace WebRole1.Controllers
{
    public class QuestionController : Controller
    {

        private Model1 db = new Model1();
        private ILog log = LogManager.GetLogger("log");

        //Professor:----------------------------------------------------------------------

        //displays all questions of one professor that are templates, Search string for question.title
        [HttpGet]
        public ActionResult Index(string Search="")
        {
            if (Session["type"] == null)
            {
                log.Error("Session missing");
                return RedirectToAction("Login", "Account");
            }
            if (Session["type"].ToString() != "Professor")
            {
                log.Error("wrong user type");
                return RedirectToAction("Logout", "Account");
            }
            var parameters = from m in db.Parameters select m;
            if (parameters.Any())
            {
                Parameter par = parameters.First();
                ViewBag.unlock = par.UnlockNumber;
            }
            string email = Session["email"].ToString();
            var users = from m in db.Users select m;
            users = users.Where(s => s.Mail.Equals(email));
            if (users.Any())
            {
                User user = users.First();
                int id = user.IdU;
                var questions = from m in db.Questions select m;
                questions = questions.Where(s => s.IsClone == 0);
                questions = questions.Where(s => s.IdU == id);
                if (string.Compare(Search, "") != 0)
                {
                    questions = questions.Where(s => s.Title.Contains(Search));
                }
                ViewBag.srch = Search;
                return View(questions);
            }
            log.Error("user not existing in db");
            return RedirectToAction("Logout", "Account");
        }

        //displays edit for specific question that is not locked nad not a clone
        [HttpGet]
        public ActionResult Editor(int? id)
        {
            if (Session["type"] == null)
            {
                log.Error("Session missing");
                return RedirectToAction("Login", "Account");
            }
            if (Session["type"].ToString() != "Professor")
            {
                log.Error("wrong user type");
                return RedirectToAction("Logout", "Account");
            }
            if (id == null)
            {
                log.Error("id parameter missing");
                return RedirectToAction("Logout", "Account");
            }
            var questions = from m in db.Questions select m;
            questions = questions.Where(s => s.IdP == id);
            string email = Session["email"].ToString();
            var users = from m in db.Users select m;
            users = users.Where(s => s.Mail.Equals(email));
            var parameters = from m in db.Parameters select m;
            if (parameters.Any())
            {
                Parameter par = parameters.First();
                ViewBag.k = par.AnswerNumber;
            }
            
            if (users.Any() && questions.Any())
            {
                User user = users.First();
                Question question = questions.First();
                if (question.IsLocked == 1)
                    return RedirectToAction("Logout", "Account");
                if (question.IdU==user.IdU)
                    return View(question);
            }
            log.Error("question and user not mergable in database");
            return RedirectToAction("Logout", "Account");
        }

        //displays details of specifick question
        [HttpGet]
        public ActionResult Details(int? id)
        {
            if (Session["type"] == null)
            {
                log.Error("Session missing");
                return RedirectToAction("Login", "Account");
            }
            if (Session["type"].ToString() != "Professor")
            {
                log.Error("wrong user type");
                return RedirectToAction("Logout", "Account");
            }
            if (id == null)
            {
                log.Error("missing id parameter");
                return RedirectToAction("Logout", "Account");
            }
            var questions = from m in db.Questions select m;
            questions = questions.Where(s => s.IdP == id);
            string email = Session["email"].ToString();
            var users = from m in db.Users select m;
            users = users.Where(s => s.Mail.Equals(email));
            var parameters = from m in db.Parameters select m;
            if (parameters.Any())
            {
                Parameter par = parameters.First();
                ViewBag.unlock = par.UnlockNumber;
            }

            if (users.Any() && questions.Any())
            {
                User user = users.First();
                Question question = questions.First();
                if (question.IsClone == 1)
                {
                    ViewBag.clone = 1;
                }
                else
                {
                    ViewBag.clone = 0;
                }
                if (question.IdU == user.IdU)
                    return View(question);
            }
            log.Error("question and user not mergeable in db");
            return RedirectToAction("Logout", "Account");
        }

        //index:ajax locks and unlocks questions 
        [HttpPost]
        public ActionResult IndexUp(int id) {
            if (Session["type"] == null)
            {
                log.Error("Session missing");
                return Content("error2", "text/plain");
            }
            if (Session["type"].ToString() != "Professor")
            {
                log.Error("wrong user type");
                return Content("error2", "text/plain");
            }
            var questions = from m in db.Questions select m;
            questions = questions.Where(s => s.IdP == id);
            string email = Session["email"].ToString();
            var users = from m in db.Users select m;
            users = users.Where(s => s.Mail.Equals(email));
            var parameters = from m in db.Parameters select m;
            Parameter par = null;
            if (parameters.Any())
            {
                par = parameters.First();
            }
            else
            {
                log.Error("parameters missing in db, initialize again db");
                return Content("error2", "text/plain");
            }
            if (users.Any() && questions.Any())
            {
                User user = users.First();
                Question question = questions.First();
                if (question.IsLocked == 0)
                {
                    log.Error("question is locked id: "+question.IdP);
                    return Content("error2", "text/plain");
                }
                if (question.IsClone == 1)
                {
                    log.Error("question is clone id: "+question.IdP);
                    return Content("error2", "text/plain");
                }
                if (question.IdU == user.IdU)
                {
                    if (user.Balans >= par.UnlockNumber)
                    {
                        user.Balans -= par.UnlockNumber;
                        question.IsLocked = 0;
                        db.SaveChanges();   
                        Session["token"] = user.Balans.ToString();
                        return Content(user.Balans.ToString(), "text/plain");
                    }
                    return Content("error", "text/plain");
                }
            }
            log.Error("question and user not mergeable");
            return Content("error2", "text/plain");
        }

        //displays create question page
        [HttpGet]
        public ActionResult Create()
        {
            if (Session["type"] == null)
            {
                log.Error("Session missing");
                return RedirectToAction("Login", "Account");
            }
            if (Session["type"].ToString() != "Professor")
            {
                log.Error("wrong user type");
                return RedirectToAction("Logout", "Account");
            }
            var parameters = from m in db.Parameters select m;
            if (parameters.Any()) {
                Parameter par = parameters.First();
                ViewBag.k = par.AnswerNumber;
                return View();
            }
            log.Error("parameters missing initialize again db");
            return RedirectToAction("Logout", "Account");
        }

        //editor for question, submiting
        [HttpPost]
        public ActionResult Editor(int? id, HttpPostedFileBase file)
        {
            if (Session["type"] == null)
            {
                log.Error("Session missing");
                return RedirectToAction("Login", "Account");
            }
            if (Session["type"].ToString() != "Professor")
            {
                log.Error("wrong user type");
                return RedirectToAction("Logout", "Account");
            }
            if (id == null)
            {
                log.Error("id argument missing");
                return RedirectToAction("Logout", "Account");
            }
            var questions = from m in db.Questions select m;
            questions = questions.Where(s => s.IdP == id);
            string email = Session["email"].ToString();
            var users = from m in db.Users select m;
            users = users.Where(s => s.Mail.Equals(email));
            User user = null;
            Question question1 = null;
            if (users.Any() && questions.Any())
            {
                user = users.First();

Implementation/IepProjekat/WebRole1/Views/Publish/Blackboard.cshtml
@model IEnumerable<WebRole1.Models.Published>

@{
    ViewBag.Title = "Blackboard";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Blackboard</h2>

<div class="container">
    <div class="row" id="boardPlace">
        @foreach (var item in Model.Reverse())
        {
        <div class="col-sm-4 panel-pad-10">
            <a href="@Url.Action("Answering", "Question")?id=@item.IdP&chan=@item.IdC" style="text-decoration:none; color:black;">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        Channel: @item.Channel.Name
                    </div>
                    <div class="panel-body text-center" style="height:180px; overflow:hidden;">
                        <span class="text-danger h4" style="text-transform:uppercase"><b>@item.Question.Title</b></span>
                        <br/>
                        <br />
                        <div style="text-align:left; margin-left:10px;"><span class="h5">@item.Question.Text</span></div>
                        <br/>
                        @foreach (var it in item.Question.Answers)
                        {
                            <div style="text-align:left; margin-left:10px;"><span class="h6">@it.Tag) @it.Text</span></div>
                        }
                    </div>
                    <div class="panel-footer">Published (UTC): @Html.ValueFor(modelItem => item.PubTime, "{0:dd/MMM/yyyy HH:mm}")</div>
                </div>
            </a>
        </div>
        }
        
    </div>
</div>


@section scripts {
    <!--Script references. -->
    <!--The jQuery library is required and is referenced by default in _Layout.cshtml. -->
    <!--Reference the SignalR library. -->
    <script src="~/Scripts/jquery.signalR-2.2.2.min.js"></script>
    <!--Reference the autogenerated SignalR hub script. -->
    <script src="~/signalr/hubs"></script>
    <!--SignalR script to update the chat page and send messages.-->
    <script>
        $(function () {
            // Reference the auto-generated proxy for the hub.
            var chat = $.connection.boardHub;
            // Create a function that the hub can call back to display messages.
            chat.client.boardfresh = function (idQuest, idChann, channame, title, text, answers, time) {
                var element = document.getElementById("boardPlace");
                var newStuff = '<div class="col-sm-4 panel-pad-10"><a href="@Url.Action("Answering", "Question")?id=' + idQuest + '&chan='+idChann+'" style="text-decoration:none; color:black;">';
                newStuff += '<div class="panel panel-default"><div class="panel-heading">Channel: ' + channame + '</div><div class="panel-body text-center" style="height:180px; overflow:hidden;">';
                newStuff += '<span class="text-danger h4" style="text-transform:uppercase"><b>' + title + '</b></span><br/><br /><div style="text-align:left; margin-left:10px;"><span class="h5">' + text + '</span></div><br/>';
                var ans = answers.split("<NewAns>");
                for (var i = 0, len = ans.length; i < len; i++) {
                    newStuff += '<div style="text-align:left; margin-left:10px;"><span class="h6">' + ans[i] + '</span></div>';
                }
                newStuff += '</div> <div class="panel-footer">Published (UTC): ' + time + '</div></div></a></div>';
                element.innerHTML = newStuff + element.innerHTML;
            };
            // Start the connection.
            $.connection.hub.start().done(function () {
                @foreach (var item in ViewBag.chann) {
                    WriteLiteral("chat.server.joingroup('");
                    @item
                    WriteLiteral("');");
                }
            });
    });
        // This optional function html-encodes messages for display in the page.
        //function htmlEncode(value) {
          //  var encodedValue = $('<div />').text(value).html();
            //return encodedValue;
        //}
    </script>
}

Implementation/IepProjekat/WebRole1/Views/Publish/Index.cshtml
@model IEnumerable<WebRole1.Models.Channel>

@{
    ViewBag.Title = "Publish";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Choose channels:</h2>
@using (Html.BeginForm("Index", "Publish", FormMethod.Post, new { id = "FormQ", role = "form" }))
{
    <input type="number" style="display:none" name="idQ" value="@ViewBag.idQ"/>
    <div class="container">
        <div class="row">
            <div class="col-xs-12 col-sm-6 col-md-6" style="height:400px; overflow: auto">
                <table class="table">
                    <tr>
                        <th>
                            Id
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.Name)
                        </th>
                        <th>
                            Publish
                        </th>
                    </tr>

                    @{var i = 0;}

                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.IdC)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Name)
                            </td>
                            <td>
                                <input type="checkbox" id="checkbox1" value="@item.IdC" name="box @i"/>
                            </td>
                        </tr>
                        i++;
                    }
                </table>
            </div>
        </div>
    </div>

    <div class="form-group">
        <button type="button" class="btn btn-primary" id="beck"><span class="glyphicon glyphicon-arrow-left"></span>&nbsp Back</button>
        <button type="submit" class="btn btn-primary" id="butt1"><span class="glyphicon glyphicon-share-alt"></span>&nbsp Publish</button>
    </div>
 }

    @if (ViewBag.msg != null)
    {
        <label>@ViewBag.msg</label>
    }

<script src="~/Scripts/jquery-1.10.2.js" type="text/javascript"></script>
<script type="text/javascript">

    $(document).ready(function () {

        $('#beck').on('click', function clckF() {
            window.location = "@Url.Action("Index", "Question")";
        });
    });
</script>