Implementation/IepProjekat/WebRole1/Controllers/AdminController.cs
using log4net;
using System.Data.Entity;
using System.Linq;
using System.Web.Mvc;
using WebRole1.Models;

namespace WebRole1.Controllers
{
    public class AdminController : Controller
    {
        private Model1 db = new Model1();
        private ILog log = LogManager.GetLogger("log");

        //Configuration page display, seting parameters
        [HttpGet]
        public ActionResult Configuration()
        {
            if (Session["type"] == null)
            {
                log.Error("Session missing");
                return RedirectToAction("Login", "Account");
            }
            if (Session["type"].ToString() != "Administrator")
            {
                log.Error("wrong user type");
                return RedirectToAction("Logout", "Account");
            }
            var users = from m in db.Parameters select m;
            Parameter parameter = users.First();
            return View(parameter);
        }

        //Approvals display page
        [HttpGet]
        public ActionResult Approvals(int Search = 0)
        {
            if (Session["type"] == null)
            {
                log.Error("Session missing");
                return RedirectToAction("Login", "Account");
            }
            if (Session["type"].ToString() != "Administrator")
            {
                log.Error("wrong user type");
                return RedirectToAction("Logout", "Account");
            }
            var users = from m in db.Users select m;
            //in case search==1 display only not activated (status==0) users
            if (Search == 0)
            {
                ViewBag.chBox = "0";
                return View(users);
            }
            else
            {
                users = users.Where(s => s.Status == 0);
                ViewBag.chBox = "1";
                return View(users);
            }
        }

        //Configuration save changes
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Configuration([Bind(Include = "IdP,AnswerNumber,SilverNumber,GoldNumber,PlatinumNumber,UnlockNumber,PremiumNumber")] Parameter parameter)
        {
            if (Session["type"] == null)
            {
                log.Error("Session missing");
                return RedirectToAction("Login", "Account");
            }
            if (Session["type"].ToString() != "Administrator")
            {
                log.Error("wrong user type");
                return RedirectToAction("Logout", "Account");
            }
            if (ModelState.IsValid)
            {
                db.Entry(parameter).State = EntityState.Modified;
                db.SaveChanges();
                ViewBag.message = "Saved";
            }
            else
            {
                ViewBag.message = "Not saved";
            }   
            return View();
        }

        //Approval:ajax submiting user registration
        [HttpPost]
        public ActionResult Approvals(string email, string type)
        {
            if (Session["type"] == null)
            {
                log.Error("Session missing");
                return Content("error", "text/plain");
            }
            if (Session["type"].ToString() != "Administrator")
            {
                log.Error("wrong user type");
                return Content("error", "text/plain");
            }
            if (type != "Student" && type != "Professor")
            {
                return Content("error", "text/plain");
            }
            var users = from m in db.Users select m;
            //find user by email and check if registration is not confirmed
            users = users.Where(s => s.Mail.Equals(email));
            users = users.Where(s => s.Status == 0);
            if (users.Any())
            {
                User user = users.First();
                user.Type = type;
                user.Status = 1;
                db.SaveChanges();
                return Content("Success", "text/plain");
            }
            log.Error("User not found");
            return Content("error", "text/plain");
        }
    }
}

Implementation/IepProjekat/WebRole1/Controllers/OrderController.cs
using log4net;
using System.Linq;
using System.Net;
using System.Net.Mail;
using System.Web.Mvc;
using System.Web.Security;
using WebRole1.Models;

namespace WebRole1.Controllers
{
    public class OrderController : Controller
    {
        private Model1 db = new Model1();
        private ILog log = LogManager.GetLogger("log");

        //Displays page for chooseing package
        [HttpGet]
        public ActionResult Index()
        {
            if (Session["type"] == null)
            {
                log.Error("Session missing");
                return RedirectToAction("Login", "Account");
            }
            if (Session["type"].ToString() == "Administrator")
            {
                log.Error("wrong user type");
                return RedirectToAction("Logout", "Account");
            }
            var parameters = from m in db.Parameters select m;
            if (parameters.Any())
            {
                Parameter par = parameters.First();
                ViewBag.silver = par.SilverNumber;
                ViewBag.gold = par.GoldNumber;
                ViewBag.platinum = par.PlatinumNumber;
                return View();
            }
            log.Error("parameters not found in database");
            return RedirectToAction("Login", "Account");
        }

        //Checks witch package and builds link for centili
        [HttpPost]
        public ActionResult Index(int package) {
            if (Session["type"] == null)
            {
                log.Error("Session missing");
                return RedirectToAction("Login", "Account");
            }
            if (Session["type"].ToString() == "Administrator")
            {
                log.Error("wrong user type");
                return RedirectToAction("Logout", "Account");
            }
            string email = Session["email"].ToString();
            var users = from m in db.Users select m;
            users = users.Where(s => s.Mail.Equals(email));
            var parameters = from m in db.Parameters select m;
            if (parameters.Any())
            {
                Parameter par = parameters.First();
                ViewBag.silver = par.SilverNumber;
                ViewBag.gold = par.GoldNumber;
                ViewBag.platinum = par.PlatinumNumber;
                if (users.Any())
                {
                    User user = users.First();
                    string link = "";
                    string api = "aee8499dc5f97cd80d74c64ce7f3545d";
                    int price = 0;
                    int number = 0;
                    switch (package)
                    {
                        case 1:
                            number = ViewBag.silver;
                            price = 50 * ViewBag.silver;
                            break;
                        case 2:
                            number = ViewBag.gold;
                            price = 50 * ViewBag.gold;
                            break;
                        case 3:
                            number = ViewBag.platinum;
                            price = 50 * ViewBag.platinum;
                            break;
                    }
                    if (price == 0) {
                        log.Error("package number not exsisting");
                        return RedirectToAction("Logout", "Account");
                    }                
                    Order order = new Order();
                    order.IdU = user.IdU;
                    order.Number = number;
                    order.Price = price;
                    order.State = "waiting on";
                    db.Orders.Add(order);
                    db.SaveChanges();
                    string userid = FormsAuthentication.HashPasswordForStoringInConfigFile(user.Mail + user.Password + order.IdO, "SHA1");
                    order.Tag = userid;
                    db.SaveChanges();
                    //string returnUrl = HttpContext.Request.Url.Scheme + "://" + HttpContext.Request.Url.Authority + Url.Action("PayRply", "Order");
                    link = "http://api.centili.com/payment/widget?apikey=" + api + "&price=50&userid="+userid;
                    return Redirect(link);
                }
            }
            log.Error("parameters not found in database");
            return RedirectToAction("Login", "Account");
        }

        //get answer from centili about transaction and redirect user
        [HttpGet]
        public ActionResult PayReply(string userid, string status) {
            var orders = from m in db.Orders select m;
            orders = orders.Where(s => s.Tag.Equals(userid));
            Order order = null;
            if (!orders.Any())
            {
                log.Error("order not exsisting in db, tag: "+userid);
                return RedirectToAction("Logout", "Account");
            }
            else
            {
                order = orders.First();
            }
            if (string.Compare(order.State, "waiting on") != 0)
            {
                log.Error("order already done, tag: "+userid);
                return RedirectToAction("Logout", "Account");
            }
            if (string.Compare(status, "success") == 0)
            {
                order.User.Balans += order.Number;
                order.State = "realized";
                if (Session["token"] != null)
                {
                    Session["token"] = order.User.Balans.ToString();
                }
                ViewBag.message = "Transaction successfull";
                ViewBag.button = "Continue";
                string userMail = order.User.Mail;
                string textSubject = "Transaction successfull";
                string textMail = "You bought " + order.Number + " tokens for " + order.Price + "RSD";
                MailMessage msg = new MailMessage("studioneer@gmail.com", userMail, textSubject, textMail);
                SmtpClient sc = new SmtpClient("smtp.gmail.com", 587);
                sc.UseDefaultCredentials = false;
                NetworkCredential cre = new NetworkCredential("studioneer@gmail.com", "aspmvc5!");
                sc.Credentials = cre;
                sc.EnableSsl = true;
                sc.Send(msg);

            }
            else
            {
                order.State = "rejected";
                ViewBag.message = "Something went wrong";
                ViewBag.button = "Try again";
            }
            db.SaveChanges();
            if (Session["type"] == null)
            {
                log.Error("Session missing");
                return RedirectToAction("Login", "Account");
            }
            if (Session["type"].ToString() == "Administrator")
            {
                log.Error("wrong user type");
                return RedirectToAction("Logout", "Account");
            }
            return View();
        }

        //displays all orders from one user
        [HttpGet]
        public ActionResult Orders() {
            if (Session["type"] == null)
            {
                log.Error("Session missing");
                return RedirectToAction("Login", "Account");
            }
            if (Session["type"].ToString() == "Administrator")
            {
                log.Error("wrong user type");
                return RedirectToAction("Logout", "Account");
            }
            string email = Session["email"].ToString();
            var users = from m in db.Users select m;
            users = users.Where(s => s.Mail.Equals(email));
            var parameters = from m in db.Parameters select m;
            if (users.Any())
            {
                User user = users.First();
                var orders = from m in db.Orders select m;
                orders = orders.Where(s => s.IdU == user.IdU);
                return View(orders);
            }
            log.Error("user not found in db");
            return RedirectToAction("Login", "Account");
        }
    }
}

Implementation/IepProjekat/WebRole1/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Studioneer", "Login", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    
                    @if (@HttpContext.Current.Session["type"] != null)
                    {                        
                        if (@HttpContext.Current.Session["type"].ToString() == "Administrator")
                        {
                            <li>@Html.ActionLink("Configuration", "Configuration", "Admin")</li>
                            <li>@Html.ActionLink("Approvals", "Approvals", "Admin")</li>
                        }
                        if (@HttpContext.Current.Session["type"].ToString() == "Professor")
                        {
                            <li>@Html.ActionLink("Questions", "Index", "Question")</li>
                            <li>@Html.ActionLink("Channels", "Index", "Channel")</li>
                        }
                        if (@HttpContext.Current.Session["type"].ToString() == "Student")
                        {
                            <li>@Html.ActionLink("New channels", "ActiveChannels", "Channel")</li>
                            <li>@Html.ActionLink("Subs", "Subscribed", "Channel")</li>
                            <li>@Html.ActionLink("Board", "Blackboard", "Publish")</li>
                            <li>@Html.ActionLink("Answers", "Answers", "Question")</li>
                        }
                        if ((@HttpContext.Current.Session["type"].ToString() == "Student") || @HttpContext.Current.Session["type"].ToString() == "Professor")
                        {                      
                            <li>@Html.ActionLink("Shop", "Index", "Order")</li>
                            <li>@Html.ActionLink("Orders", "Orders", "Order")</li>
                            <li>@Html.ActionLink("Info", "Info", "Account")</li>
                        }
                    }
                </ul>
                @Html.Partial("_LoginPartial");
            </div>
        </div>
    </div>
    <div class="container body-content">

        @if (@HttpContext.Current.Session["type"] != null)
        {
            if ((@HttpContext.Current.Session["type"].ToString() == "Student") || @HttpContext.Current.Session["type"].ToString() == "Professor")
            {
                <h3 class="pull-right">@HttpContext.Current.Session["username"].ToString(), <span id="numtoken">@HttpContext.Current.Session["token"].ToString()</span> tokens.</h3>
            }
        }
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Studioneer</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>